import { EventCategory, Events } from "@/interfaces/events";

export const event_category: EventCategory[] = [
  {
    id: 1,
    event_category_name: "birthday party",
  },
  {
    id: 2,
    event_category_name: "movie show",
  },
  {
    id: 3,
    event_category_name: "singing contest",
  },
  {
    id: 4,
    event_category_name: "Dance performance",
  },
  {
    id: 5,
    event_category_name: "Stand-up comedy",
  },
  {
    id: 6,
    event_category_name: "Magic show",
  },
];

export const events: Events[] = [
  {
    id: 1,
    event_name: "John's Birthday Party",
    date: "10/15/2023",
    image_url: "/img/events/img-1.png",
    event_category_id: 1,
  },
  {
    id: 2,
    event_name: "the red one movie show",
    image_url: "/img/events/img-2.png",
    date: "10/15/2023",
    event_category_id: 2,
  },
  {
    id: 3,
    event_name: "Singing Contest",
    image_url: "/img/events/img-3.png",
    date: "10/15/2023",
    event_category_id: 3,
  },
  {
    id: 4,
    event_name: "Dance Performance",
    image_url: "/img/events/img-4.png",
    date: "10/15/2023",
    event_category_id: 4,
  },
  {
    id: 5,
    event_name: "Stand-up Comedy Night",
    image_url: "/img/events/img-5.png",
    date: "10/15/2023",
    event_category_id: 5,
  },
  {
    id: 6,
    event_name: "Magic Show Extravaganza",
    image_url: "/img/events/img-6.png",
    date: "10/15/2023",
    event_category_id: 6,
  },
  {
    id: 7,
    event_name: "John's Birthday Party",
    date: "10/15/2023",
    image_url: "/img/events/img-1.png",
    event_category_id: 1,
  }, {
    id: 8,
    event_name: "the red one movie show",
    image_url: "/img/events/img-2.png",
    date: "10/15/2023",
    event_category_id: 2,
  },
  {
    id: 9,
    event_name: "Singing Contest",
    image_url: "/img/events/img-3.png",
    date: "10/15/2023",
    event_category_id: 3,
  },
  {
    id: 10,
    event_name: "Dance Performance",
    image_url: "/img/events/img-4.png",
    date: "10/15/2023",
    event_category_id: 4,
  },
  {
    id: 11,
    event_name: "Stand-up Comedy Night",
    image_url: "/img/events/img-5.png",
    date: "10/15/2023",
    event_category_id: 5,
  },
  {
    id: 12,
    event_name: "Magic Show Extravaganza",
    image_url: "/img/events/img-6.png",
    date: "10/15/2023",
    event_category_id: 6,
  },
  { 
    id: 13,
    event_name: "John's Birthday Party",
    date: "10/15/2023",
    image_url: "/img/events/img-1.png",
    event_category_id: 1,
  },
  {
    id: 14,
    event_name: "the red one movie show",
    image_url: "/img/events/img-2.png",
    date: "10/15/2023",
    event_category_id: 2,
  },
  {
    id: 15,
    event_name: "Singing Contest",
    image_url: "/img/events/img-3.png",
    date: "10/15/2023",
    event_category_id: 3,
  },
  {
    id: 16,
    event_name: "Dance Performance",
    image_url: "/img/events/img-4.png",
    date: "10/15/2023",
    event_category_id: 4,
  },
  {
    id: 17,
    event_name: "Stand-up Comedy Night",
    image_url: "/img/events/img-5.png",
    date: "10/15/2023",
    event_category_id: 5,
  },
  {
    id: 18,
    event_name: "Magic Show Extravaganza",
    image_url: "/img/events/img-6.png",
    date: "10/15/2023",
    event_category_id: 6,
  }, 
  /* make sample data till 30 id */
  {
    id: 19,
    event_name: "John's Birthday Party",
    date: "10/15/2023",
    image_url: "/img/events/img-1.png",
    event_category_id: 1,
  },
  {
    id: 20,
    event_name: "the red one movie show",
    image_url: "/img/events/img-2.png",
    date: "10/15/2023",
    event_category_id: 2,
  },
  {
    id: 21,
    event_name: "Singing Contest",
    image_url: "/img/events/img-3.png",
    date: "10/15/2023",
    event_category_id: 3, 
  }, 
  {
    id: 22,
    event_name: "Dance Performance",
    image_url: "/img/events/img-4.png",
    date: "10/15/2023",
    event_category_id: 4,
  }, 
  {
    id: 23,
    event_name: "Stand-up Comedy Night",
    image_url: "/img/events/img-5.png",
    date: "10/15/2023",
    event_category_id: 5,
  }, {
    id: 24,
    event_name: "Magic Show Extravaganza",
    image_url: "/img/events/img-6.png",
    date: "10/15/2023",
    event_category_id: 6,
  }, {
    id: 25,
    event_name: "John's Birthday Party",
    date: "10/15/2023",
    image_url: "/img/events/img-1.png",
    event_category_id: 1,
  }, {
    id: 26,
    event_name: "the red one movie show",
    image_url: "/img/events/img-2.png",
    date: "10/15/2023",
    event_category_id: 2,
  }, {
    id: 27,
    event_name: "Singing Contest",
    image_url: "/img/events/img-3.png",
    date: "10/15/2023",
    event_category_id: 3,
  },
  {
    id: 28,
    event_name: "Dance Performance",
    image_url: "/img/events/img-4.png",
    date: "10/15/2023",
    event_category_id: 4,
  },
  {
    id: 29,
    event_name: "Stand-up Comedy Night",
    image_url: "/img/events/img-5.png",
    date: "10/15/2023",
    event_category_id: 5,
  },
  {
    id: 30,
    event_name: "Magic Show Extravaganza",
    image_url: "/img/events/img-6.png",
    date: "10/15/2023",
    event_category_id: 6,
  }
];
